platform :ios, '8.0'
target 'DankAssMap' do
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
pod 'GoogleMaps'
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
